import type { Exercise, Fundamental } from './types';

export const fundamentalsC: Fundamental[] = [
  {
    id: 'estrutura',
    icon: '🏗️',
    title: 'Estrutura básica de um programa C',
    summary: 'Todo programa em C começa com a inclusão de bibliotecas e a função main(). O main() é o ponto de entrada — onde o programa começa a executar. Ao terminar, retornamos 0 para indicar que tudo ocorreu bem.',
    example: `#include <stdio.h>   // biblioteca para printf e scanf\n\nint main() {\n    // Seu código vai aqui\n    printf(\"Olá, mundo!\\n\");\n    return 0;           // 0 = programa terminou sem erros\n}`,
  },
  {
    id: 'printf',
    icon: '🖨️',
    title: 'Exibindo dados na tela (printf)',
    summary: 'O printf() exibe texto formatado na tela. Usamos "%d" para inteiros, "%f" para decimais e "%s" para strings. O \\n cria uma nova linha.',
    example: `#include <stdio.h>\n\nint main() {\n    int idade = 20;\n    float altura = 1.75;\n\n    printf(\"Idade: %d\\n\", idade);\n    printf(\"Altura: %.2f\\n\", altura);  // .2f = 2 casas decimais\n    printf(\"Nome: %s\\n\", \"Maria\");\n    return 0;\n}`,
  },
  {
    id: 'scanf',
    icon: '⌨️',
    title: 'Lendo dados do usuário (scanf)',
    summary: 'O scanf() lê o que o usuário digita. Atenção: sempre coloque & antes da variável (exceto em strings/vetores). Isso indica ao C onde na memória guardar o valor lido.',
    example: `#include <stdio.h>\n\nint main() {\n    int numero;\n    float preco;\n\n    printf(\"Digite um número: \");\n    scanf(\"%d\", &numero);    // & = endereço de memória\n\n    printf(\"Digite o preço: \");\n    scanf(\"%f\", &preco);\n\n    printf(\"Número: %d, Preço: %.2f\\n\", numero, preco);\n    return 0;\n}`,
  },
  {
    id: 'variaveis',
    icon: '📦',
    title: 'Variáveis e Tipos de Dados',
    summary: 'Em C você precisa declarar o tipo da variável antes de usá-la. Os tipos principais são: int (inteiro), float (decimal simples), double (decimal de precisão dupla) e char (caractere).',
    example: `#include <stdio.h>\n\nint main() {\n    int         idade    = 25;       // número inteiro\n    float       altura   = 1.75f;   // decimal (simples)\n    double      salario  = 3500.50; // decimal (dupla precisão)\n    char        letra    = 'A';     // um único caractere\n    char        nome[50] = \"João\";  // string (vetor de char)\n\n    printf(\"Idade: %d\\n\", idade);\n    printf(\"Altura: %.2f\\n\", altura);\n    printf(\"Salário: %.2lf\\n\", salario);  // %lf para double\n    printf(\"Letra: %c\\n\", letra);\n    printf(\"Nome: %s\\n\", nome);\n    return 0;\n}`,
  },
  {
    id: 'operacoes',
    icon: '➕',
    title: 'Operações Matemáticas',
    summary: 'C usa os mesmos operadores básicos: + - * / e % (módulo/resto). Atenção: divisão entre dois inteiros descarta a parte decimal! Para ter decimal, use float ou double.',
    example: `#include <stdio.h>\n\nint main() {\n    int a = 10, b = 3;\n\n    printf(\"%d + %d = %d\\n\", a, b, a + b);   // 13\n    printf(\"%d - %d = %d\\n\", a, b, a - b);   // 7\n    printf(\"%d * %d = %d\\n\", a, b, a * b);   // 30\n    printf(\"%d / %d = %d\\n\", a, b, a / b);   // 3 (inteiro!)\n    printf(\"%d %% %d = %d\\n\", a, b, a %% b);  // 1 (resto)\n\n    // Para divisão com decimal:\n    float resultado = (float)a / b;\n    printf(\"%.2f\\n\", resultado);  // 3.33\n    return 0;\n}`,
  },
  {
    id: 'controle',
    icon: '🔀',
    title: 'Estruturas de Controle',
    summary: 'if/else toma decisões com base em condições. O for e while repetem blocos de código. Estes são os blocos de construção de qualquer lógica em C.',
    example: `#include <stdio.h>\n\nint main() {\n    int nota = 7;\n\n    // if/else\n    if (nota >= 7) {\n        printf(\"Aprovado!\\n\");\n    } else {\n        printf(\"Reprovado.\\n\");\n    }\n\n    // for: repete 5 vezes\n    for (int i = 1; i <= 5; i++) {\n        printf(\"%d \", i);  // 1 2 3 4 5\n    }\n    printf(\"\\n\");\n\n    // while\n    int x = 0;\n    while (x < 3) {\n        printf(\"x = %d\\n\", x);\n        x++;\n    }\n    return 0;\n}`,
  },
];

export const exercisesC: Exercise[] = [
  {
    id: 1,
    title: 'Olá Mundo',
    description: 'Escreva um programa em C que exiba "Olá, Mundo!" na tela.',
    tips: ['#include <stdio.h>', 'int main()', 'printf', 'return 0'],
    lesson: {
      concept: 'Estrutura básica: include, main, printf e return.',
      example: `#include <stdio.h>\n\nint main() {\n    printf(\"Olá, Mundo!\\n\");\n    return 0;\n}`,
      instructions: 'Escreva a estrutura básica do programa C e use a função printf.',
      expectedOutput: 'Olá, Mundo!',
      steps: ['Include', 'Main', 'Printf', 'Return'],
    },
  },
  {
    id: 2,
    title: 'Número Informado',
    description: 'Faça um programa que leia um número inteiro e exiba: "O número informado foi: X".',
    tips: ['scanf("%d", &n)', 'printf'],
    lesson: {
      concept: 'O scanf() lê dados e o & indica o endereço de memória.',
      example: `#include <stdio.h>\n\nint main() {\n    int n;\n    scanf(\"%d\", &n);\n    printf(\"O número informado foi: %d\\n\", n);\n    return 0;\n}`,
      instructions: 'Declare um inteiro e use scanf e printf.',
      expectedOutput: 'O número informado foi: X',
      steps: ['Declare', 'Scanf', 'Printf'],
    },
  },
  {
    id: 3,
    title: 'Soma de Dois Números',
    description: 'Leia dois números inteiros e exiba a soma deles.',
    tips: ['int a, b, soma;', 'soma = a + b;'],
    lesson: {
      concept: 'Soma aritmética simples.',
      example: `#include <stdio.h>\n\nint main() {\n    int a, b; scanf(\"%d %d\", &a, &b);\n    printf(\"Soma: %d\\n\", a + b);\n    return 0;\n}`,
      instructions: 'Leia dois valores e mostre a soma.',
      expectedOutput: 'Soma: X',
      steps: ['Leia A', 'Leia B', 'Some', 'Mostre'],
    },
  },
  {
    id: 4,
    title: 'Média Bimestral',
    description: 'Leia 4 notas bimestrais e calcule a média.',
    tips: ['float', '%f', '/ 4.0'],
    lesson: {
      concept: 'Média com float.',
      example: `#include <stdio.h>\n\nint main() {\n    float n1, n2, n3, n4; scanf(\"%f %f %f %f\", &n1, &n2, &n3, &n4);\n    printf(\"Média: %.2f\\n\", (n1+n2+n3+n4)/4.0);\n    return 0;\n}`,
      instructions: 'Leia 4 floats e calcule a média.',
      expectedOutput: 'Média: X.XX',
      steps: ['Leia notas', 'Media', 'Mostre'],
    },
  },
  {
    id: 5,
    title: 'Metros para Centímetros',
    description: 'Leia em metros e converta para centímetros.',
    tips: ['* 100'],
    lesson: {
      concept: 'Conversão básica.',
      example: `#include <stdio.h>\n\nint main() {\n    float m; scanf(\"%f\", &m);\n    printf(\"%.2f cm\\n\", m * 100);\n    return 0;\n}`,
      instructions: 'Multiplique o valor lido por 100.',
      expectedOutput: 'X.XX cm',
      steps: ['Leia metros', 'Converta', 'Mostre'],
    },
  },
  {
    id: 6,
    title: 'Área do Círculo',
    description: 'Leia o raio de um círculo e calcule sua área.',
    tips: ['#define PI 3.14159', 'raio * raio'],
    lesson: {
      concept: 'Área com constante.',
      example: `#include <stdio.h>\n#define PI 3.14\nint main() {\n    float r; scanf(\"%f\", &r);\n    printf(\"Area: %.2f\\n\", PI * r * r);\n    return 0;\n}`,
      instructions: 'Use a fórmula PI * r * r.',
      expectedOutput: 'Area: X.XX',
      steps: ['Defina PI', 'Leia r', 'Calcule', 'Mostre'],
    },
  },
  {
    id: 7,
    title: 'Salário Mensal',
    description: 'Leia valor/hora e horas e calcule salário.',
    tips: ['*'],
    lesson: {
      concept: 'Cálculo de salário.',
      example: `#include <stdio.h>\nint main() {\n    float v, h; scanf(\"%f %f\", &v, &h);\n    printf(\"Salario: R$ %.2f\\n\", v * h);\n    return 0;\n}`,
      instructions: 'Multiplique valor por horas.',
      expectedOutput: 'Salario: R$ X.XX',
      steps: ['Leia v', 'Leia h', 'Multiplique', 'Mostre'],
    },
  },
  {
    id: 8,
    title: 'Fahrenheit para Celsius',
    description: 'Leia F e converta para C.',
    tips: ['(F - 32) * 5 / 9'],
    lesson: {
      concept: 'Conversão térmica.',
      example: `#include <stdio.h>\nint main() {\n    float f; scanf(\"%f\", &f);\n    printf(\"C: %.2f\\n\", (f-32)*5/9.0);\n    return 0;\n}`,
      instructions: 'Aplique a fórmula de Fahrenheit para Celsius.',
      expectedOutput: 'C: X.XX',
      steps: ['Leia F', 'Fórmula', 'Mostre'],
    },
  },
  {
    id: 9,
    title: 'Salário com Descontos',
    description: 'Calcule salário líquido com descontos: 11% IR, 8% INSS, 5% Sind.',
    tips: ['0.11', '0.08', '0.05'],
    lesson: {
      concept: 'Descontos percentuais.',
      example: `#include <stdio.h>\nint main() {\n    float b; scanf(\"%f\", &b);\n    printf(\"Líquido: %.2f\\n\", b * 0.76);\n    return 0;\n}`,
      instructions: 'Calcule o bruto e subtraia os percentuais.',
      expectedOutput: 'Líquido: X.XX',
      steps: ['Bruto', 'IR', 'INSS', 'Sind', 'Liquido'],
    },
  },
  {
    id: 10,
    title: 'Vetor de Inteiros',
    description: 'Leia 10 inteiros em um vetor e exiba-os.',
    tips: ['int v[10]', 'for'],
    lesson: {
      concept: 'Trabalhando com arrays.',
      example: `#include <stdio.h>\nint main() {\n    int v[10]; for(int i=0; i<10; i++) scanf(\"%d\", &v[i]);\n    for(int i=0; i<10; i++) printf(\"%d \", v[i]);\n    return 0;\n}`,
      instructions: 'Use um loop para ler e outro para mostrar.',
      expectedOutput: 'X X X...',
      steps: ['Vetor', 'Loop 1', 'Loop 2'],
    },
  },
  {
    id: 11,
    title: 'Maior Valor do Vetor',
    description: 'Leia 10 inteiros e encontre o maior.',
    tips: ['maior = v[0]', 'if(v[i] > maior)'],
    lesson: {
      concept: 'Busca em vetor.',
      example: `#include <stdio.h>\nint main() {\n    int v[10], m; for(int i=0; i<10; i++) scanf(\"%d\", &v[i]);\n    m = v[0]; for(int i=1; i<10; i++) if(v[i]>m) m=v[i];\n    printf(\"Maior: %d\", m); return 0;\n}`,
      instructions: 'Compare cada elemento com o atual maior.',
      expectedOutput: 'Maior: X',
      steps: ['Vetor', 'Assume 1º', 'Loop', 'Update', 'Mostre'],
    },
  },
  {
    id: 12,
    title: 'Ponteiros Básicos',
    description: 'Leia N, aponte P para N e exiba o valor de P.',
    tips: ['int *p', 'p = &n'],
    lesson: {
      concept: 'Endereços de memória.',
      example: `#include <stdio.h>\nint main() {\n    int n; int *p = &n; scanf(\"%d\", &n);\n    printf(\"%d\", *p); return 0;\n}`,
      instructions: 'Use um ponteiro para acessar o valor da variável.',
      expectedOutput: 'X',
      steps: ['Declare', 'Ponteiro', 'Assinale', 'Mostre *p'],
    },
  },
  {
    id: 13,
    title: 'Struct — Aluno',
    description: 'Crie uma struct Aluno e mostre os dados.',
    tips: ['typedef struct', 'aluno.nota'],
    lesson: {
      concept: 'Registros heterogêneos.',
      example: `#include <stdio.h>\ntypedef struct { char n[20]; float nt; } Aluno;\nint main() { Aluno a; scanf(\"%s %f\", a.n, &a.nt);\nprintf(\"%s: %.1f\", a.n, a.nt); return 0; }`,
      instructions: 'Agrupe nome e nota em uma estrutura.',
      expectedOutput: 'Nome: X, Nota: X',
      steps: ['Struct', 'Leia', 'Mostre'],
    },
  },
];
